version: '3'

services:
    db:
        image: postgres
        ports:
            - '5432:5432'
        environment:
          - POSTGRES_DB=${DB_NAME}
          - POSTGRES_USER=${DB_USER}
          - POSTGRES_PASSWORD=${DB_PASSWORD}
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/movies
        ports:
            - "8000:8000"
        depends_on:
            - db
            - rabbitmq
        links:
            - db:db
            - rabbitmq:rabbitmq
    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - 5672:5672
            - 15672:15672
    celery-worker:
        build: .
        command: celery -A Movie_App worker -l info
        volumes:
            - .:/movies
        restart: always
        depends_on:
            - db
            - web
            - rabbitmq

            